if(argument1=1)
{
    q=0.01;
    r=100;
    rr=300;
    re=200;
}
if(argument1=2)
{
    q=0.005;
    r=200;
    rr=600;
    re=400;
}
if(argument1=3)
{
    q=0.0025;
    r=400;
    rr=1200;
    re=800;
}
aaa = surface_create(rr,re);
surface_set_target(aaa);
draw_clear(c_black);
for(xs=-2;xs<1;xs=xs+q){
    for(ys=-1;ys<1;ys=ys+q){
        x1=xs;
        y1=ys;
        
        for(counter=0;counter<argument0;counter=counter+1)
        {
            tx = x1;
            x1=((x1*x1-y1*y1)+xs);
            y1=(2*(tx*y1)+ys);
            if(point_distance(x1,y1,0,0)>2)
            {
                break;
            }
        }
        if(point_distance(x1,y1,0,0)>2)
        {
            if(global.color=="R")
            {
                if (counter > 0)
                {
                draw_point_color(r*xs+(2*r),r*ys+r,make_color_rgb(5+(counter*8),0,0))
                }
               
            }
            if(global.color=="G")
            {
                draw_point_color(r*xs+(2*r),r*ys+r,make_color_rgb(0,5+(counter*8),0))
            }
            if(global.color=="B")
            {
                draw_point_color(r*xs+(2*r),r*ys+r,make_color_rgb(0,0,5+(counter*8)))
            }
            if(global.color=="P")
            {
                draw_point_color(r*xs+(2*r),r*ys+r,make_color_rgb(5+(counter*8),0,5+(counter*8)))
            }
            if(global.color=="Y")
            {
                draw_point_color(r*xs+(2*r),r*ys+r,make_color_rgb(5+(counter*8),5+(counter*8),0))
            }
            if(global.color=="T")
            {
                draw_point_color(r*xs+(2*r),r*ys+r,make_color_rgb(0,5+(counter*8),5+(counter*8)))
            }
            if(global.color=="W")
            {
                draw_point_color(r*xs+(2*r),r*ys+r,make_color_rgb(5+(counter*8),5+(counter*8),5+(counter*8)))
            }
        }
        else
        {
      //  draw_point_color(r*xs+(2*r),r*ys+r,make_color_rgb(random_range(200,255),0,0))
            //draw_point_color(r*xs+(2*r),r*ys+r,c_black);
        }
        if(xs==0&&ys==0)
        {
            //draw_point_color(r*xs+(2*r),r*ys+r,c_red);
        }
    }
}
view_enabled = false;
surface_reset_target();
